app <- ShinyDriver$new("../")
app$snapshotInit("test_abs")

app$snapshot()

app$uploadFile(file1 = "../../test_data/butterfly_small-experiment-table.csv")
app$snapshot()

app$setInputs(last_tick = TRUE, wait_=FALSE, values_=FALSE)
app$setInputs(x_var = "corridor_width", wait_=FALSE, values_=FALSE)
app$setInputs(y_var = "mean_elevation_of_turtles", wait_=FALSE, values_=FALSE)
app$setInputs(points = FALSE, wait_=FALSE, values_=FALSE)
app$setInputs(lines = TRUE, wait_=FALSE, values_=FALSE)
app$setInputs(group_var = "q")
app$setInputs(points = TRUE)
app$setInputs(lines = FALSE, wait_=FALSE, values_=FALSE)
app$snapshot()

app$setInputs(ren_from = "corridor_width", wait_=FALSE, values_=FALSE)
app$setInputs(ren_to = "corridor width", wait_=FALSE, values_=FALSE)
app$setInputs(rename = "click")
app$setInputs(ren_from = "mean_elevation_of_turtles", wait_=FALSE, values_=FALSE)
app$setInputs(ren_to = "elevation", wait_=FALSE, values_=FALSE)
app$setInputs(rename = "click")
app$setInputs(x_var = "corridor_width", wait_=FALSE, values_=FALSE)
app$setInputs(y_var = "mean_elevation_of_turtles", wait_=FALSE, values_=FALSE)
app$setInputs(group_var = "q", wait_=FALSE, values_=FALSE)
app$setInputs(summary_tab = TRUE)
app$setInputs(points = TRUE, wait_=FALSE, values_=FALSE)
app$setInputs(lines = FALSE, wait_=FALSE, values_=FALSE)
app$snapshot()
