library(shinytest2)

test_that("{shinytest2} recording: Butterfly Corridor", {
  app <- AppDriver$new(variant = platform_variant(), name = "Butterfly Corridor",
      seed = 12345678, height = 1009, width = 1167,
      wait = TRUE)
  app$upload_file(file1 = "test_data/butterfly_small-experiment-table.csv")
  app$expect_values()
  app$set_inputs(ren_from = "corridor_width")
  app$set_inputs(ren_to = "Corridor width")
  app$click("rename")
  app$expect_values()
  app$set_inputs(ren_from = "mean_elevation_of_turtles")
  app$set_inputs(ren_to = "Elevation")
  app$click("rename")
  app$expect_values()
  app$set_inputs(x_var = "q")
  app$set_inputs(y_var = "corridor_width")
  app$set_inputs(points = TRUE)
  app$set_inputs(lines = FALSE)
  app$expect_screenshot()
  app$set_inputs(lines = TRUE)
  app$expect_screenshot()
  app$set_inputs(error_bars = "error bars")
  app$expect_screenshot()
  app$set_inputs(lines = FALSE)
  app$expect_screenshot()
  app$set_inputs(points = FALSE)
  app$expect_screenshot()
  app$set_inputs(lines = TRUE)
  app$set_inputs(error_bars = "bands")
  app$expect_screenshot()
  app$set_inputs(points = TRUE)
  app$expect_screenshot()
  app$set_inputs(lines = FALSE)
  app$expect_screenshot()
  app$set_inputs(error_bars = "none")
  app$set_inputs(points = TRUE)
  app$set_inputs(lines = FALSE)
  app$set_inputs(x_var = "corridor_width")
  app$set_inputs(y_var = "mean_elevation_of_turtles")
  app$set_inputs(group_var = "q")
  app$set_inputs(summary_tab = TRUE)
  app$expect_values()
  app$expect_screenshot()
})
