library(shinytest2)

test_that("{shinytest2} recording: Full test suite", {
  app <- AppDriver$new(variant = platform_variant(),
      seed = 12345678, height = 1009, width = 1167,
      wait = TRUE,
      screenshot_args = list(selector = "html", delay = 1.0)
      # expect_values_screenshot_args = list(selector = "html", delay = 1.0)
      )
  app$upload_file(file1 = "../../../test_data/butterfly_small-experiment-table.csv")
  Sys.sleep(2)
  app$expect_values(name="initial",
                    screenshot_args = list(selector = "html", delay = 1.0))
  app$set_inputs(ren_from = "corridor_width")
  app$set_inputs(ren_to = "Corridor width")
  app$click("rename")
  app$expect_values(name="rename-cw",
                    screenshot_args = list(selector = "html", delay = 1.0))
  app$set_inputs(ren_from = "mean_elevation_of_turtles")
  app$set_inputs(ren_to = "Elevation")
  app$click("rename")
  app$expect_values(name="rename-elev",
                    screenshot_args = list(selector = "html", delay = 1.0))
  app$set_inputs(x_var = "q")
  app$set_inputs(y_var = "corridor_width")
  app$set_inputs(points = TRUE)
  app$set_inputs(lines = FALSE)
  app$expect_screenshot(selector=".plot", name="ss-points-error-none")
  app$set_inputs(lines = TRUE)
  app$expect_screenshot(selector=".plot", name="ss-points-lines-error-none")
  app$set_inputs(error_bars = "error bars")
  app$expect_screenshot(selector=".plot", name="ss-points-lines-error-bars")
  app$set_inputs(lines = FALSE)
  app$expect_screenshot(selector=".plot", name="ss-points-error-bars")
  app$set_inputs(points = FALSE)
  app$expect_screenshot(selector=".plot", name="ss-error-bars")
  app$set_inputs(lines = TRUE)
  app$set_inputs(error_bars = "bands")
  app$expect_screenshot(selector=".plot", name="ss-lines-error-bands")
  app$set_inputs(points = TRUE)
  app$expect_screenshot(selector=".plot", name="ss-points-lines-error-bands")
  app$expect_values(name="points-lines-error-bands",
                    screenshot_args = list(selector = "html", delay = 1.0))
  app$set_inputs(lines = FALSE)
  app$expect_screenshot(selector=".plot", name="ss-points-error-bands")
  app$set_inputs(error_bars = "none")
  app$set_inputs(points = TRUE)
  app$set_inputs(lines = FALSE)
  app$set_inputs(x_var = "corridor_width")
  app$set_inputs(y_var = "mean_elevation_of_turtles")
  app$set_inputs(group_var = "q")
  app$set_inputs(summary_tab = TRUE)
  app$expect_values(name="cw-vs-elev-by-q",
                    screenshot_args = list(selector = "html", delay = 1.0))
  app$expect_screenshot(selector=".plot", name="ss-cw-vs-elev-by-q")
})
