image: rocker/tidyverse

test:
  script:
    - R -e 'install.packages(c("DT", "janitor", "shinyalert", "shinytest"))'
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
